["alt/buildpack-deps"]
skip-branches = [ "p9" ]

["alt/distroless-base"]
skip-branches = [ "p9" ]

["alt/distroless-builder"]
skip-branches = [ "p9" ]

["alt/distroless-devel"]
skip-branches = [ "p9" ]

["alt/distroless-gotop"]
skip-branches = [ "p9" ]

["alt/distroless-static"]
skip-branches = [ "p9" ]

["alt/distroless-true"]
skip-branches = [ "p9" ]

["alt/gitea"]
skip-branches = [ "p9" ]

["alt/node"]
skip-branches = [ "p9" ]

["alt/unit"]
skip-branches = [ "p9" ]

["alt/prometheus"]
skip-branches = [ "p9" ]

["alt/registry"]
skip-branches = [ "p9" ]

["k8s/cert-manager-cainjector"]
skip-branches = [ "p9" ]

["k8s/cert-manager-controller"]
skip-branches = [ "p9" ]

["k8s/cert-manager-webhook"]
skip-branches = [ "p9" ]

["k8s/coredns"]
skip-branches = [ "p9" ]

["k8s/etcd"]
skip-branches = [ "p9" ]

["k8s/kube-apiserver"]
skip-branches = [ "p9" ]

["k8s/kube-controller-manager"]
skip-branches = [ "p9" ]

["k8s/kube-proxy"]
skip-branches = [ "p9" ]

["k8s/kube-scheduler"]
skip-branches = [ "p9" ]

["k8s/pause"]
skip-branches = [ "p9" ]
