["k8s/kube-apiserver"]
p10 = [ "v1.26.3" ]
sisyphus = [ "v1.26.3" ]

["k8s/kube-controller-manager"]
p10 = [ "v1.26.3" ]
sisyphus = [ "v1.26.3" ]

["k8s/kube-scheduler"]
p10 = [ "v1.26.3" ]
sisyphus = [ "v1.26.3" ]

["k8s/kube-proxy"]
p10 = [ "v1.26.3" ]
sisyphus = [ "v1.26.3" ]

["k8s/pause"]
p10 = [ "3.7" ]
sisyphus = [ "3.7" ]

["k8s/etcd"]
p10 = [ "3.5.6-0" ]
sisyphus = [ "3.5.6-0" ]

["k8s/coredns"]
p10 = [ "v1.8.6" ]
sisyphus = [ "v1.8.6" ]

["k8s/cert-manager-cainjector"]
p10 = [ "v1.9.1" ]
sisyphus = [ "v1.9.1" ]

["k8s/cert-manager-controller"]
p10 = [ "v1.9.1" ]
sisyphus = [ "v1.9.1" ]

["k8s/cert-manager-webhook"]
p10 = [ "v1.9.1" ]
sisyphus = [ "v1.9.1" ]

["k8s/flannel"]
p10 = [ "v0.21.4" ]
sisyphus = [ "v0.21.4" ]

["k8s/flannel-cni-plugin"]
p10 = [ "v1.1.2" ]
sisyphus = [ "v1.1.2" ]
