["k8s/kube-apiserver"]
p10 = [ "v1.24.8" ]
sisyphus = [ "v1.24.8" ]

["k8s/kube-controller-manager"]
p10 = [ "v1.24.8" ]
sisyphus = [ "v1.24.8" ]

["k8s/kube-scheduler"]
p10 = [ "v1.24.8" ]
sisyphus = [ "v1.24.8" ]

["k8s/kube-proxy"]
p10 = [ "v1.24.8" ]
sisyphus = [ "v1.24.8" ]

["k8s/pause"]
p10 = [ "3.7" ]
sisyphus = [ "3.7" ]

["k8s/etcd"]
p10 = [ "3.5.5-0" ]
sisyphus = [ "3.5.5-0" ]

["k8s/coredns"]
p10 = [ "v1.8.6" ]
sisyphus = [ "v1.8.6" ]

["k8s/cert-manager-cainjector"]
p10 = [ "v1.9.1" ]
sisyphus = [ "v1.9.1" ]

["k8s/cert-manager-controller"]
p10 = [ "v1.9.1" ]
sisyphus = [ "v1.9.1" ]

["k8s/cert-manager-webhook"]
p10 = [ "v1.9.1" ]
sisyphus = [ "v1.9.1" ]

["k8s/flannel"]
p10 = [ "v0.19.2" ]
sisyphus = [ "v0.19.2" ]

["k8s/flannel-cni-plugin"]
p10 = [ "v1.2.0" ]
sisyphus = [ "v1.2.0" ]
