from = "{{ registry }}{{ organization }}/distroless-static:{{ branch }}"
builder-install-packages = [
    "glibc-core",
    '{{if_branches(["p10"], "glibc-nss")}}',
    "glibc-timezones",
    "libselinux",
    '{{if_branches(["p9", "p10"], "libssl1.1")}}',
    '{{if_branches(["sisyphus"], "libssl1.1")}}',
    '{{if_branches(["sisyphus"], "libssl3")}}',
    "tzdata",
    "zlib",
]
packages = [
    "glibc-core",
    '{{if_branches(["p10"], "glibc-nss")}}',
    "glibc-pthread",
    "glibc-timezones",
    "tzdata",
    "zlib",
]
timezone = "Europe/Moscow"
